language: python
os:
- linux
dist: trusty
python:
- '3.5'
- '3.6'
before install:
- echo "$PATH"
install:
- pip install coveralls
script:
- python setup.py install
- nosetests --with-coverage --cover-package=barrnap ./test_barrnap.py -v
after_success: coveralls
deploy:
  - provider: pypi
    user: NickWaters
    password:
      secure: "DtcOQdQ8n0nmGnH5G5xdCdOoT60XKkfN5JklSSqJVa31HQrjJ6/OhMJrw7O7Tu8XNncEusCOL4AHvEF2TC8GoXhTUHQqCW01bTRcjhe4owTr9OQPn+/zds13+V9xqE/vmQnXmOJV3eCOkZXz2xMtY+YIMrpKV1MuD4XRYDww7tFgrUckChDmNR+M69zLrnf/D9MNIKYaSvyVW/Ojecuv9qmCyUrhX5okcN7AoOyP1yK03JnnfqaKU8BHp+e5vrbOCZwa7yby2i60mVtAyfsaEmlzmkgyseifLu//qdy1SaJLiAGX8IsTaKyO9U1kh/9zhegWUfflcEIx8XVTdBNVzNTpInNzAl3sc8VHcjbfWrrEg9cO2wxk4B+68456r62LQanwApCwUXv9cFSHgMs4fYa/7vJitmghOQF1Ej5xYpNTipbiveIjfPxWj06EHHA5P6xj9Jhur5rKkueMtDEO/8JMbirEvabdw8ylQ6mfh9JIlapHEm7nLr5zucyvayMfWhOlEjFGUjAx4awM69bsoWsbJ1ov8druEeiMLy0LlV7JW9c0GbSqU8z6MBVKn3SJDhOxWacA77je/pAJ70xnpThidY9izAKfEzaFE1loHrm80nsJcGv1iQ53Zp99AIFZKG2PLfk90BGNxSLl/EQASgPTN2OQhXFX0r2ly8A5MxA="
    on:
      tags: true
      all_branches: true
  - provider: pypi
    user: NickWaters
    server: https://test.pypi.org/legacy/
    password:
      secure:  "sZ0SAU2qKg+0C473rhT6qBNgmFuMxT7g5cRNdxHohHPr4vOUluD9P2p3lU44F75yAwtro4GtSOgfZuAVERoowHVS44rd/5EVez14I6KJ9cdHhSGvWkHQMfXFkZWjYRiznEAiI4poegELC8OOs97FeSAqrGWgQMdANBcDun3DtKESHWiHobypMBCqhQQj6H1N754Z2Je4sE4JcTZloizcPhIK/EzgQQi0NUFOBkVOpz1shUeGgKrpkbswkFnk5WduFJcctX9DNWPam1d7/avCLpUyVbaUDyekh/YYipUJEmsWkm8RffravYPkxZyvmNRuIkMipfPgn+3IDrAZcJPcn9rm3B23cq3ZRWgyOVVtHaAijTp9BREpTXJXrkch8Mkp6uUrPeiy9FdXIlTlVWBqU1vyT4kN5RHY/WTpaHNEYQIA4M0JYkYnWkEAucAmXx+dc94h3I0bRE8wE5gEmbervFrhMdoSGlNB6pHfDie7RD9IWOunR5YjXd15VAwjJ0PIzkvVNB7IjuRCaSiVeUZehG35h5P6qO85ZxdQBcbWWwKERiarT6CBfhJjHFsCCBiv7WOhBcE87moZGFYQgVcyw8tCS454p5GF2bz0NYM2OnerlyqW39EmzQkjjlpvqcA/0nfeuQNwLB3Ay8oSuG+igFtaTx3s1M4w1eHLvSBrG90="
    on:
      all_branches: true
